### PR TITLE
Updated the markers document for this year's competition

### PR DESCRIPTION
**Pull request by what-does-that-do**
Changed the link in markers.md from last year's zip file to this year's pdf of the markers.

Also, fixed a minor formatting issue in the website landing page - I have removed a random q stuck in the middle of the social links.

### CODE REVIEW

**Review by Minion3665 — CHANGES_REQUESTED** [review]
This is a lot better, however I notice you don't have any arena wall markers included. Is this intentional or an oversight (they should be 100-123)?

image

**Comment by what-does-that-do** [comment]
> This is a lot better, however I notice you don't have any arena wall markers included. Is this intentional or an oversight (they should be 100-123)?
> 
> image

This is likely an oversight, however I have just been asked to add this file to the website ASAP, so I'd add it on and then I can update it later if I find out it is indeed an oversight. It might be intentional for some reason.

**Review by Minion3665 — APPROVED** [review]
In that case, let's get this merged. Can I trust you to chase-up on whether this is intentional?

**Comment by what-does-that-do** [comment]
> In that case, let's get this merged. Can I trust you to chase-up on whether this is intentional?

Yes, as I'll be in college tomorrow so I can ask :)

**Pull request merged**
