### PR TITLE
Clarified setting resolution, updates to USB Camera

### PR DESCRIPTION
**Pull request by what-does-that-do**
This brings the docs in line with the changes to `vision.py`. Key changes:

- Clarified that resolutions are different on USB Cameras
- Added a dedicated "USB Cameras" section
- Added instructions and info about plugging in, setting up, resolutions, focal lengths and calibration
- Embedded code to calibrate focal lengths

Note that I won't merge this until the patch has been released, due to syntax changes on the new patch. These changes have also been copied into sheep.

### CODE REVIEW

**Comment by what-does-that-do** [comment]
Why is this failing checks?  My changes shouldn't cause the build errors...?

**Review by MostlyTurquoise — APPROVED** [review]
Changes look good, see my comments on sheep, I don't really know why it is not building. Very strange,

**Comment by Minion3665** [comment]
looks like it's "yet another LFS issue:tm:"

this time it's an internal server error, I'm going to restart it to see if that fixes it

**Comment by Minion3665** [comment]
still the same error

```
5:41:12 PM: warn: sizes cache did not exist at /opt/build/cache/image-sizes.json
5:41:13 PM: info: found 2 normal file(s) and 989 lfs file(s) [skipped 0 cached file(s)]
5:41:13 PM: info: requesting lfs info for 989 images...
5:41:41 PM: (node:22479) UnhandledPromiseRejectionWarning: StatusCodeError: 500 - undefined
5:41:41 PM:     at new StatusCodeError (/opt/build/repo/node_modules/request-promise-core/lib/errors.js:32:15)
5:41:41 PM:     at Request.plumbing.callback (/opt/build/repo/node_modules/request-promise-core/lib/plumbing.js:104:33)
5:41:41 PM:     at Request.RP$callback [as _callback] (/opt/build/repo/node_modules/request-promise-core/lib/plumbing.js:46:31)
5:41:41 PM:     at Request.self.callback (/opt/build/repo/node_modules/request/request.js:185:22)
5:41:41 PM:     at Request.emit (events.js:314:20)
5:41:41 PM:     at Request.<anonymous> (/opt/build/repo/node_modules/request/request.js:1154:10)
5:41:41 PM:     at Request.emit (events.js:314:20)
5:41:41 PM:     at IncomingMessage.<anonymous> (/opt/build/repo/node_modules/request/request.js:1076:12)
5:41:41 PM:     at Object.onceWrapper (events.js:420:28)
5:41:41 PM:     at IncomingMessage.emit (events.js:326:22)
5:41:41 PM: (node:22479) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

**Comment by what-does-that-do** [comment]
Maybe we should add the job of changing our LFS provider along with node updates to our long list of robocon problems...

**Comment by Minion3665** [comment]
> Maybe we should add the job of changing our LFS provider along with node updates to our long list of robocon problems...

maybe so, for now it's probably worth running the `images:sizes` script locally to check what's going on

**Pull request merged**
